package org.sewtha.planmaker.client;

public enum ProducerOrConsumerEnum {

	SOLAR_HEATING, SOLAR_PV, SOLAR_FARMING, SOLAR_BIOMASS, ONSHORE_WIND,
	OFFSHORE_WIND_SHALLOW, OFFSHORE_WIND_DEEP, HYDRO_LOWLAND, HYDRO_HIGHLAND,
	TIDAL, BARRAGE, LAGOONS, WAVE, GEOTHERMAL, CLEAN_COAL, NUCLEAR, SOLAR_DESERTS, 
	WASTE, PUMPED_HEAT, WOOD, ELECCONV_LOSSES, FOSSIL_FUELS, ELECTHINGS, HEATING_SAVINGS, 
	TRANSPORT_SAVINGS;
}
